"""
What’s the number?

Concepts needed: print, while loop, if/else statements, random function, input/ output

This is a guessing game that the user plays with the program/computer. 
The program generates a random number using the random function. The user tries to guess it by inputting a value. 
The program then indicates whether the guess is right or not. If it is wrong, then the program should tell how off the guess was. 
If it is right, there should be another positive indicator. You can place a limit on the number of guesses allowed.
You will also need functions to compare the inputted number with the guessed number, to compute the difference between the two, 
and to check whether an actual number was inputted or not. 
"""

import random

score = 0
gamesPlayed = 0

def inputnum():
    flag = True
    while flag:
        guess = input("Try to guess the number generated by computer: ")
        if guess.isdigit():
            flag = False
            return  int(guess)

def game():
    # generating random number, different from randint as this does not include the end point
    print("Computer has generated a random number between 1 and 10. Get it right in 5 tries!")
    num = random.randrange( 1, 11)

    # Asking user for a guess
    tries = 5
    global score
    global gamesPlayed
    gamesPlayed += 1
    while(tries!=0):
        tries -= 1
        guess = inputnum()
        print(guess == num)
        if(guess == num):
            print("Congratulations!!")
            score = score + 1
            playAgain()
            break
        elif(tries == 0):
            print("You are out of tries! Play again (Y/N)?")
            response = input()
            playAgain()
            break
        else:
            if(guess < num):
                print("The guess is less than the number")
            else:
                print("The guess is more than the num")
    
def playAgain():
    response = input("Wanna play again? Type Y/N?\n")
    if(response == 'Y'):
        game()
    else:
        print("Thank You for playing. Your score: ", score , "/" , gamesPlayed)

if __name__ == '__main__':
    print("***Welcome to the Game Expo!***\n")
    print("We have got a guessing game for you today\n")
    game()